### PR TITLE
Make debug output dynamic

### PR DESCRIPTION
**Pull request by wimrijnders**
This centralizes all library code between `#ifdef DEBUG` blocks.
    
A new class `Debug` is added to the Library. This allows for debug output enabling in the code, without having to recompile the library.
    
The debug output can be turned on and off with a call to `Debug::enable()`. It is also possible to redirect debug output to a logfile.
    
In particular, it gets rid of `#ifdef DEBUG` statements in the library code. The way is now open to remove `DEBUG=1` as a make option, which currently doesn't do anything any more.
    
Code has been added to example program `Tri` to show usage.

### CODE REVIEW

**Comment by wimrijnders** [comment]
As an aside, the `Debug` class has some `doxygen`-style header comments. This should give you some idea as to how the commenting will be when (if?) I add doc-generation.

**Comment by wimrijnders** [comment]
TBH the more I think about this the uglier I find it. I think I have to rethink what I want to do here.

The idea is good, namely to be able to specify the target of the debug output and to be able to turn it on and off. But this implementation is off-putting.

At a minimum, I want to be able to extract the source and target code output as it happens in `compileKernel()` without having to resort to a recompile with `DEBUG=1`. Perhaps you have an idea how to do that.

**Comment by wimrijnders** [comment]
**NOTE:** Please do not accept & merge this yet (if you intend to); see #29 first.

**Comment by mn416** [comment]
> At a minimum, I want to be able to extract the source and target code output as it happens in compileKernel() without having to resort to a recompile with DEBUG=1. Perhaps you have an idea how to do that.

You could make `compileKernel()` take an optional parameter that, to begin with, just includes logging options, e.g. whether logging is enabled and if so where should the log be written to.

**Comment by wimrijnders** [comment]
Yes, that would work. But I have realized it would be better to refactor a bit first for more flexibility, see #26.

In addition, I would prefer a more general approach, that can be used in other code parts as well, not just `compileKernel()`.

**Comment by wimrijnders** [comment]
Actually, your suggestion is fine as a first step. But the  thing is that `compileKernel()` get called in the constructor of `struct Kernel`, so you would need to pass in there as well.

Actually, that may not be too much of an issue. It just appears a little roundabout to me. I would prefer a method in `Kernel` that creates the output by request, but I don't see a way to do that right now.

**Comment by mn416** [comment]
It's only a suggestion, feel free to explore other solutions, I don't have any strong opinions on this.

**Comment by wimrijnders** [comment]
Hokay, will think on this.

Heh! Our first conflicts to resolve! :laughing:

**Comment by wimrijnders** [comment]
@mn416 The best I can think of right now, is to define a separate call for printing output, e.g.:

```C++
template <typename... ts>
pretty(void (*f)(ts... params), const char *filename = nullptr);
```
This would make the output generation explicit and by request, so the `#if DEBUG` can be removed in the kernel code.

If no filename specified, the output goes to `stdout`.
Internally, this calls `compile()` with a file pointer as extra parameter. The drawback is that a kernel is compiled and then discarded, just to generate the output.

Tell me what you think about this.

**Comment by mn416** [comment]
The `Kernel` class has access to both the source code and target code inside member variables.  So why not just add a `pretty()` method to the `Kernel` class?

**Comment by wimrijnders** [comment]
Hey you're awake. I had this feeling you're in a completely different timezone from me.

Because the kernel doesn't store the source code in any way. It's discarded in `compileKernel()` as soon as the target code has been assembled.

**Comment by mn416** [comment]
Ok, I see

**Comment by wimrijnders** [comment]
Ah, now I remember. This is what I meant (ctor `Kernel`):

```c++
  // Save pointer to source program for interpreter
    #ifdef EMULATION_MODE
    sourceCode = body;
    #else
    sourceCode = NULL;
    #endif
```

This is just a matter of removing the `#ifdef`. I hope that's OK with you.

**Comment by wimrijnders** [comment]
Ooh, I just noticed that there's a single global stack `stmtStack`. This is going to be problematic if multiple kernels are compiled in a program.

I propose to add a stack member to `struct Kernel`, so that there can be multiple separate kernel instances. I actually feel that this is kind of urgent.

**Comment by wimrijnders** [comment]
I see issues here as well:

```c++
    // Obtain the AST
    Stmt* body = stmtStack.top();
    stmtStack.pop();
```

`pop()` deletes the pointer returned by `top()`, so `body` is actually pointing to unallocated memory (IMHO upon code examination, feel free to prove otherwise).

This is in dire need of unit tests.

**Comment by mn416** [comment]
Multiple kernels should be fine and, as you've spotted, the `compile()` function is not thread-safe.

But the stack needs to be a global variable, because it's being used to construct the abstract syntax tree.  All the QPU code that the user writes is being shovelled into the abstract syntax tree behind the scenes.

This is pretty fundamental to QPULib.  It might be called a hack, but it's exactly what makes the approach work in the first place.

**Comment by wimrijnders** [comment]
OK so far. I will study that part in more detail to see if I can make more sense of it.

For now, a message somewhere saying that 'QPULib is not thread-safe' will suffice.

**Comment by mn416** [comment]
> For now, a message somewhere saying that 'QPULib is not thread-safe' will suffice.

The `compile()` function is not thread-safe, but in theory, once created, you could call kernels from different threads.

**Comment by wimrijnders** [comment]
Understood. Please excuse my paranoia (which for programming I regard as a good trait to have).

**Comment by wimrijnders** [comment]
@mn416 I have the feeling that a 'usage notes` section in the docs would be a good idea. Somewhat akin to your 'usage strategies' proposal but with more practical notes (e.g. gotcha's). I can think of 3 things already to put into it. The note *CPU/GPU memory split* in 'Getting Started' would fit in there as well.

**Comment by wimrijnders** [comment]
I'm quite happy with the `Kernel::pretty()` approach. Will let it rest till tomorrow so I can scrutinize is with a clear mind before committing.

**Comment by wimrijnders** [comment]
@mn416 This is fit for review again. Notes:

- Got rid of the `Debug` class
- Output of source/target code via method `Kernel::pretty()`
- Output is now not dependent upon specifying `DEBUG=1` on build
- Example call in `Tri.cpp`
- Please note define `NEVER_USED`. Can this function be removed?

**Comment by wimrijnders** [comment]
> Maybe I was paranoid about memory leaks.

:smile:  I have no problems with paranoia wrt coding. I regard it as a good thing. Embrace it, brother!

> It might be worth creating an example that involves creation of two kernels, and testing it. I'm not sure I've ever tried it before, but it should work.

I smell a unit test here. I think `Rot3D` is a good candidate here, since it has multiple versions.

What I'm reading between the lines is the question of how much the heap can be stressed, ie. how many kernels can actually be compiled before things go awry. This is actually a test worthy of consideration, if only to see what happens at the end.

Let's see if I can make such a test work. This is the part where I turn evil.....

----
**EDIT:** Come to think of it, `AutoTest` would be even better for this, since it generates heaps of code (no pun intended), meaningless or otherwise. Much faster way of stressing out the heap.

**Comment by wimrijnders** [comment]
`astHeap.clear()`: ok, I understand the issue here; there is no way to *un*allocate elements on the heap, thereby inhibiting reuse of heap capacity. So anything allocated will just remain there.

Glaring at the heap code right now, which is currently simple in essence. Right now, I feel that any attempt to reclaim heap memory is like opening a can of worms.....

**Comment by mn416** [comment]
> Right now, I feel that any attempt to reclaim heap memory is like opening a can of worms.....

I agree, trying to do the garbage collection manually could introduce all sorts of subtle bugs.  I don't feel the issue will bother users very often, and when it does they have a simple solution.

If I had to allow multiple ASTs, any of which can be freed at any time, then I'd probably reallocate `astHeap` for each kernel, i.e. do `astHeap = new Heap` inside the `Kernel` constructor before elaborating the kernel function.  Now every kernel has its own `astHeap` which could be freed in the destructor, or a member function.

But probably best just to leave it as is, with all calls to `astHeap.clear()` commented out.

**Comment by wimrijnders** [comment]
OK. I hope you can agree that something needs to be done for making the heaps more efficient to use. However, I suggest to defer the work for that now. I will do the following:

- remove the `clear()`  call as per your suggestion
- if necessary, increase the heap sizes, to pass the unit tests
- add an item to the TODO list for investigating the heaps later

**Pull request merged**
