### PR TITLE
Adjust 'Getting Started' for changes in makefile

### PR DESCRIPTION
**Pull request by wimrijnders**
This adjusts the code example in 'Getting Started' to the new output directories.
    
In addition, `make all` is explained and the text block has been revised.

### CODE REVIEW

**Comment by mn416** [comment]
Thanks, merged.

One suggestion on this: might you mention the process of disabling OpenGL to get things working on the Pi 3?

**Comment by wimrijnders** [comment]
Yes good point! It needs to go somewhere in the docs. Perhaps a developer's guide page with caveats.

On my TODO.

**Comment by wimrijnders** [comment]
Come to think of it, the TODO should be part of the project. Considering adding a `TODO.md` to `Docs`, is this OK by you?

**Comment by mn416** [comment]
> Come to think of it, the TODO should be part of the project. Considering adding a TODO.md to Docs, is this OK by you?

Sounds good :+1:

**Pull request merged**
