### PR TITLE
Add SFU write registers to Encoding

### PR DESCRIPTION
**Pull request by wimrijnders**
Initial changes for #43; this is not a complete solution.

This adds the definitions and handling of the four input registers for the Special Function Unit.

In addition, the following changes to `encodeDestReg()` and `encodeSrcReg()`:

- Added extensive header commenting, to document how I understand it
- Added TODOs which I think are relevant
- Reformatted code to make common blocks more visible
- Minor changes in code, mainly to aid reading

Note that this only adds the *definitions* of the special registers; no code is yet generated that actually uses them. That's the next step.

### CODE REVIEW

**Comment by mn416** [comment]
Hi @wimrijnders,

I've recently started to refactor the code to allow explicit access to the VPM by the programmer.  Unfortunately, this brings a conflict with the work you are doing in this PR: we are both going to end up changing 10-20 of the same files.  As you are reformatting code while you do it, it will be very difficult for me to keep rebasing.  I also don't know how long it will take me to complete my changes (could be a few weeks at least as I'm not able to work on this very often).

I can continue accept PRs that don't touch the library code.  But for this PR, I suggest you pursue it in a separate branch. After my code changes are done, you can resubmit a PR that I will be happy to review and merge.

I'll create a branch `development-sfu`.

**Comment by wimrijnders** [comment]
OK thanks for informing.

Yes, it's better to wait till your stuff is done. I can keep a branch for this on my side, so you don't have to bother with making any branches on your side.

I do have a request: Can the header comments be left in? Assuming you will be reviewing them, of course. I can dumb down the PR by taking out all the code changes. I'll take the responsibility of managing the code for merging at a later time.

**Comment by wimrijnders** [comment]
On the other hand, the actual code added is only 8 lines, if I leave out the reformatting.

I would like to request to add these eight lines and then I'll just stop working on the SFU. I'll roll back the reformatting and such like. And I'll pick it later after you're done.

Would that be OK?

**Comment by wimrijnders** [comment]
You know what? Never mind. I'll just put this on hold. I'll wait for your notification that you're done with the refactoring (would be happy to review).

**Comment by wimrijnders** [comment]
> I can continue accept PRs that don't touch the library code.

How about the `RegisterMap` class? This adds new files to the `Lib` but does not change the current one.

The `Debug`-mode PR, however, *does* change library files. Can you accept that one, then? It's a one-time thing to get rid of all possible warnings.

**Comment by wimrijnders** [comment]
@mn416 Now that you're with the Lib changes for DMA, can you reconsider this PR?

**Pull request closed without merging**
