### PR TITLE
Expanded debug mode in Makefile

### PR DESCRIPTION
**Pull request by wimrijnders**
This adds switches for *debug mode*, for more strict testing of the code and for enabling IDE debugging.

In particular, `-Wall` has been added. Changes have been made to the code so that all displayed warnings are handled.

Further:

- Added target `run_all` to the Makefile. This is intended to be an internal target, for running all the examples.  The goal is to check if there are any errors during runtime when running any example.
- Target `help` is now at the top of the makefile, so that it is guaranteed to run when just `make` is invoked. In addition, it is now one of the first things you see when you open the makefile.
- In the makefile, there is now a distinction between `TOOLS` and `EXAMPLES`.

### CODE REVIEW

**Comment by mn416** [comment]
Hi @wimrijnders,

I'd very much like these changes, but there too many conflicts with VPM refactoring work so this PR will have to wait.

**Comment by wimrijnders** [comment]
OK crap.

I'll do the following: revert the source code changes and just keep in the makefile changes. I'll disable the `-Wall` option or it will drive you crazy. I'll do that at a later time after you're done.

**Comment by wimrijnders** [comment]
My poor little Pi 1 is struggling to build. The Pi 3is my official backup machine, so methinks it's time to start up the Pi 2 again....should save some build time.

**Comment by wimrijnders** [comment]
@mn416 OK reverted the Library files.

This is the first time I reverted only certain files in a commit to versions of several commits ago (TIL), so I hope I did it right. Would you mind reviewing?

**Comment by wimrijnders** [comment]
I am sad to say that my Pi 2 appears to be dead. Just a little sad, since it's not exactly an expensive thing to brick. But it would havve been nice if I had a Pi 1 2 and 3 to test.

It worked for about a minute and then....nothing.

Perhaps you have an idea to fix this? It might be a recurring problem. I've tried switching bootable SD , cards, no success.

**Pull request closed without merging**
