### PR TITLE
Build QPULib as static library

### PR DESCRIPTION
**Pull request by wimrijnders**
Adjustments to the makefile to build all code under `Lib` to static library `LibQPULib.a`.
 The goal is to reduce dependencies between files, and also to speed up compilation, however slight.
    
 Also added top comment to explain output directories.

### CODE REVIEW

**Comment by wimrijnders** [comment]
Despite all the commits, this PR for for changes only in the makefile. I'm rusty with this PR-thing, probably doing something wrong.

**Comment by mn416** [comment]
Thanks, sounds like a good idea.

Related to this, I wonder if there is a "QPULib usage strategy" that we might recommend to devs who want to use QPULib in another project. Maybe they just copy the Makefile with a few adjustments, but I have to admit, I've never given much thought to this.

**Comment by mn416** [comment]
I didn't spot that this PR was for `master` rather than `development`, so I reverted it.

Can you redo this PR but for `development`?

**Comment by wimrijnders** [comment]
> "QPULib usage strategy"

Excellent idea, although I do not know yet how to word this.

What I'm trying to achieve right now is to get `QPULib` to 'industrial strength', so to speak. It should be easy for 3rd party usage and have an indication of robustness. The 'usage strategy' fits right in.

But I'm currently busy with the obvious things to fix, working to that fabled 'industrial strength'. Everything you get from me right now is for that goal. If I have any inspiration of what the usage strategy should convey, I will tell you.

....in this frame, I would eventually like to encapsulate all the `Lib`-code in a namespace `qpulib`. It may seem nonsensical right now, but if the library gets used in bigger projects, the developers will be grateful. This is forthcoming.

**Comment by wimrijnders** [comment]
> Can you redo this PR but for development?

Oops my bad. Thank you for spotting this. Please be the most evil-minded and pedantic reviewer you can possibly be.

**Pull request merged**
